apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.fullname" . }}-backend
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" . | nindent 6 }}
      app: backend

  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" . | nindent 8 }}
        app: backend

    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: 8080
              protocol: TCP

          env:
            # JWT
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: ecommerce-runtime-secret
                  key: jwt-key

            - name: Jwt__Issuer
              value: {{ .Values.jwt.issuer | quote }}

            - name: Jwt__Audience
              value: {{ .Values.jwt.audience | quote }}

            - name: Jwt__ExpiryMinutes
              value: {{ .Values.jwt.expiryMinutes | quote }}

            # MySQL
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ecommerce-runtime-secret
                  key: mysql-connection