apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-secret

type: Opaque

stringData:

  mysql-connection: "Server={{ .Values.mysql.host }};Port={{ .Values.mysql.port }};Database={{ .Values.mysql.database }};User={{ .Values.mysql.username }};Password={{ .Values.mysql.password }}"

  jwt-key: "{{ .Values.jwt.key }}"

  

  email-username: "{{ .Values.email.username }}"

  email-password: "{{ .Values.email.password }}"

  email-from-address: "{{ .Values.email.fromAddress }}"