frontend:
  replicaCount: 2

  image:
    repository: ashikdv/ecommercefrontend
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

backend:
  replicaCount: 2

  image:
    repository: ashikdv/ecommercebackend
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

mysql:
  host: "YOUR_MYSQL_HOST"
  port: 3306
  database: "ECommerceDB"
  username: "root"

jwt:
  issuer: "ECommerceBackend"
  audience: "ECommerceFrontend"
  expiryMinutes: 60

logging:
  provider: "Both"

email:
  enabled: true
  host: "smtp.gmail.com"
  port: 587
  enableSsl: true
  fromName: "ECommerce Store"

google:
  clientId: ""

ingress:
  enabled: true
  className: nginx
  frontendHost: ashik.test
  backendHost: api.ashik.test
