name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'ECommerceApp/ECommerceBackend/**'

  pull_request:
    branches:
      - main
    paths:
      - 'ECommerceApp/ECommerceBackend/**'
   # 6. Login to Docker Hub22

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ECommerceApp/ECommerceBackend

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ECommerceBackend.csproj

      - name: Build application
        run: dotnet build ECommerceBackend.csproj --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish ECommerceBackend.csproj --configuration Release --no-build --output ./publish

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ashikdv/ecommercebackend:${{ github.sha }} \
            -t ashikdv/ecommercebackend:latest \
            .

      - name: Push Docker image
        run: |
          docker push ashikdv/ecommercebackend:${{ github.sha }}
          docker push ashikdv/ecommercebackend:latest