name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'Ecommerce/Backend/**'

  pull_request:
    branches:
      - main
    paths:
      - 'Ecommerce/Backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Ecommerce/Backend

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup .NET 10
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      # 3. Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build application
      - name: Build application
        run: dotnet build --configuration Release --no-restore

      # 5. Publish application
      - name: Publish application
        run: dotnet publish --configuration Release --no-build --output ./publish

      # 6. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 7. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ashikdv/ecommercebackend:${{ github.sha }} \
            -t ashikdv/ecommercebackend:latest \
            .

      # 8. Push Docker image
      - name: Push Docker image
        run: |
          docker push ashikdv/ecommercebackend:${{ github.sha }}
          docker push ashikdv/ecommercebackend:latest